In [39]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
data = pd.read_excel("../data/digital-twin-chile-x/raw_data/2021_11_Presidencial_1V_Datos_Eleccion.xlsx", sheet_name="Votación comunal en Chile", header=6)
sorted_region_list = sorted(list(data["Región"].unique()))
for i, region in enumerate(sorted_region_list):
    print(f"REG{i+1}) {region}")

REG1) DE ANTOFAGASTA
REG2) DE ARICA Y PARINACOTA
REG3) DE ATACAMA
REG4) DE AYSEN DEL GENERAL CARLOS IBAÑEZ DEL CAMPO
REG5) DE COQUIMBO
REG6) DE LA ARAUCANIA
REG7) DE LOS LAGOS
REG8) DE LOS RIOS
REG9) DE MAGALLANES Y DE LA ANTARTICA CHILENA
REG10) DE TARAPACA
REG11) DE VALPARAISO
REG12) DE ÑUBLE
REG13) DEL BIOBIO
REG14) DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS
REG15) DEL MAULE
REG16) METROPOLITANA DE SANTIAGO

In [22]:
sorted_comuna_list = sorted(list(data["Comuna"].unique()))
for i, comuna in enumerate(sorted_comuna_list):
    print(f"COMU{i+1}) {comuna}")

COMU1) ALGARROBO
COMU2) ALHUE
COMU3) ALTO BIOBIO
COMU4) ALTO DEL CARMEN
COMU5) ALTO HOSPICIO
COMU6) ANCUD
COMU7) ANDACOLLO
COMU8) ANGOL
COMU9) ANTARTICA
COMU10) ANTOFAGASTA
COMU11) ANTUCO
COMU12) ARAUCO
COMU13) ARICA
COMU14) AYSEN
COMU15) BUIN
COMU16) BULNES
COMU17) CABILDO
COMU18) CABO DE HORNOS(EX-NAVARINO)
COMU19) CABRERO
COMU20) CALAMA
COMU21) CALBUCO
COMU22) CALDERA
COMU23) CALERA
COMU24) CALERA DE TANGO
COMU25) CALLE LARGA
COMU26) CAMARONES
COMU27) CAMIÑA
COMU28) CANELA
COMU29) CARAHUE
COMU30) CARTAGENA
COMU31) CASABLANCA
COMU32) CASTRO
COMU33) CATEMU
COMU34) CAUQUENES
COMU35) CAÑETE
COMU36) CERRILLOS
COMU37) CERRO NAVIA
COMU38) CHAITEN
COMU39) CHANCO
COMU40) CHAÑARAL
COMU41) CHEPICA
COMU42) CHIGUAYANTE
COMU43) CHILE CHICO
COMU44) CHILLAN
COMU45) CHILLAN VIEJO
COMU46) CHIMBARONGO
COMU47) CHOLCHOL
COMU48) CHONCHI
COMU49) CISNES
COMU50) COBQUECURA
COMU51) COCHAMO
COMU52) COCHRANE
COMU53) CODEGUA
COMU54) COELEMU
COMU55) COIHUECO
COMU56) COINCO
COMU57) COLBUN
COMU58) COLCHANE
COMU59) COLINA
COMU60) COLLIPULLI
COMU61) COLTAUCO
COMU62) COMBARBALA
COMU63) CONCEPCION
COMU64) CONCHALI
COMU65) CONCON
COMU66) CONSTITUCION
COMU67) CONTULMO
COMU68) COPIAPO
COMU69) COQUIMBO
COMU70) CORONEL
COMU71) CORRAL
COMU72) COYHAIQUE
COMU73) CUNCO
COMU74) CURACAUTIN
COMU75) CURACAVI
COMU76) CURACO DE VELEZ
COMU77) CURANILAHUE
COMU78) CURARREHUE
COMU79) CUREPTO
COMU80) CURICO
COMU81) DALCAHUE
COMU82) DIEGO DE ALMAGRO
COMU83) DOÑIHUE
COMU84) EL BOSQUE
COMU85) EL CARMEN
COMU86) EL MONTE
COMU87) EL QUISCO
COMU88) EL TABO
COMU89) EMPEDRADO
COMU90) ERCILLA
COMU91) ESTACION CENTRAL
COMU92) FLORIDA
COMU93) FREIRE
COMU94) FREIRINA
COMU95) FRESIA
COMU96) FRUTILLAR
COMU97) FUTALEUFU
COMU98) FUTRONO
COMU99) GALVARINO
COMU100) GENERAL LAGOS
COMU101) GORBEA
COMU102) GRANEROS
COMU103) GUAITECAS
COMU104) HIJUELAS
COMU105) HUALAIHUE
COMU106) HUALAÑE
COMU107) HUALPEN
COMU108) HUALQUI
COMU109) HUARA
COMU110) HUASCO
COMU111) HUECHURABA
COMU112) ILLAPEL
COMU113) INDEPENDENCIA
COMU114) IQUIQUE
COMU115) ISLA DE MAIPO
COMU116) ISLA DE PASCUA
COMU117) JUAN FERNANDEZ
COMU118) LA CISTERNA
COMU119) LA CRUZ
COMU120) LA ESTRELLA
COMU121) LA FLORIDA
COMU122) LA GRANJA
COMU123) LA HIGUERA
COMU124) LA LIGUA
COMU125) LA PINTANA
COMU126) LA REINA
COMU127) LA SERENA
COMU128) LA UNION
COMU129) LAGO RANCO
COMU130) LAGO VERDE
COMU131) LAGUNA BLANCA
COMU132) LAJA
COMU133) LAMPA
COMU134) LANCO
COMU135) LAS CABRAS
COMU136) LAS CONDES
COMU137) LAUTARO
COMU138) LEBU
COMU139) LICANTEN
COMU140) LIMACHE
COMU141) LINARES
COMU142) LITUECHE
COMU143) LLAILLAY
COMU144) LLANQUIHUE
COMU145) LO BARNECHEA
COMU146) LO ESPEJO
COMU147) LO PRADO
COMU148) LOLOL
COMU149) LONCOCHE
COMU150) LONGAVI
COMU151) LONQUIMAY
COMU152) LOS ALAMOS
COMU153) LOS ANDES
COMU154) LOS ANGELES
COMU155) LOS LAGOS
COMU156) LOS MUERMOS
COMU157) LOS SAUCES
COMU158) LOS VILOS
COMU159) LOTA
COMU160) LUMACO
COMU161) MACHALI
COMU162) MACUL
COMU163) MAFIL
COMU164) MAIPU
COMU165) MALLOA
COMU166) MARCHIGUE
COMU167) MARIA ELENA
COMU168) MARIA PINTO
COMU169) MARIQUINA
COMU170) MAULE
COMU171) MAULLIN
COMU172) MEJILLONES
COMU173) MELIPEUCO
COMU174) MELIPILLA
COMU175) MOLINA
COMU176) MONTE PATRIA
COMU177) MOSTAZAL
COMU178) MULCHEN
COMU179) NACIMIENTO
COMU180) NANCAGUA
COMU181) NATALES
COMU182) NAVIDAD
COMU183) NEGRETE
COMU184) NINHUE
COMU185) NOGALES
COMU186) NUEVA IMPERIAL
COMU187) O'HIGGINS
COMU188) OLIVAR
COMU189) OLLAGUE
COMU190) OLMUE
COMU191) OSORNO
COMU192) OVALLE
COMU193) PADRE HURTADO
COMU194) PADRE LAS CASAS
COMU195) PAIHUANO
COMU196) PAILLACO
COMU197) PAINE
COMU198) PALENA
COMU199) PALMILLA
COMU200) PANGUIPULLI
COMU201) PANQUEHUE
COMU202) PAPUDO
COMU203) PAREDONES
COMU204) PARRAL
COMU205) PEDRO AGUIRRE CERDA
COMU206) PELARCO
COMU207) PELLUHUE
COMU208) PEMUCO
COMU209) PENCAHUE
COMU210) PENCO
COMU211) PERALILLO
COMU212) PERQUENCO
COMU213) PETORCA
COMU214) PEUMO
COMU215) PEÑAFLOR
COMU216) PEÑALOLEN
COMU217) PICA
COMU218) PICHIDEGUA
COMU219) PICHILEMU
COMU220) PINTO
COMU221) PIRQUE
COMU222) PITRUFQUEN
COMU223) PLACILLA
COMU224) PORTEZUELO
COMU225) PORVENIR
COMU226) POZO ALMONTE
COMU227) PRIMAVERA
COMU228) PROVIDENCIA
COMU229) PUCHUNCAVI
COMU230) PUCON
COMU231) PUDAHUEL
COMU232) PUENTE ALTO
COMU233) PUERTO MONTT
COMU234) PUERTO OCTAY
COMU235) PUERTO VARAS
COMU236) PUMANQUE
COMU237) PUNITAQUI
COMU238) PUNTA ARENAS
COMU239) PUQUELDON
COMU240) PUREN
COMU241) PURRANQUE
COMU242) PUTAENDO
COMU243) PUTRE
COMU244) PUYEHUE
COMU245) QUEILEN
COMU246) QUELLON
COMU247) QUEMCHI
COMU248) QUILACO
COMU249) QUILICURA
COMU250) QUILLECO
COMU251) QUILLON
COMU252) QUILLOTA
COMU253) QUILPUE
COMU254) QUINCHAO
COMU255) QUINTA DE TILCOCO
COMU256) QUINTA NORMAL
COMU257) QUINTERO
COMU258) QUIRIHUE
COMU259) RANCAGUA
COMU260) RANQUIL
COMU261) RAUCO
COMU262) RECOLETA
COMU263) RENAICO
COMU264) RENCA
COMU265) RENGO
COMU266) REQUINOA
COMU267) RETIRO
COMU268) RINCONADA
COMU269) RIO BUENO
COMU270) RIO CLARO
COMU271) RIO HURTADO
COMU272) RIO IBAÑEZ
COMU273) RIO NEGRO
COMU274) RIO VERDE
COMU275) ROMERAL
COMU276) SAAVEDRA
COMU277) SAGRADA FAMILIA
COMU278) SALAMANCA
COMU279) SAN ANTONIO
COMU280) SAN BERNARDO
COMU281) SAN CARLOS
COMU282) SAN CLEMENTE
COMU283) SAN ESTEBAN
COMU284) SAN FABIAN
COMU285) SAN FELIPE
COMU286) SAN FERNANDO
COMU287) SAN GREGORIO
COMU288) SAN IGNACIO
COMU289) SAN JAVIER
COMU290) SAN JOAQUIN
COMU291) SAN JOSE DE MAIPO
COMU292) SAN JUAN DE LA COSTA
COMU293) SAN MIGUEL
COMU294) SAN NICOLAS
COMU295) SAN PABLO
COMU296) SAN PEDRO
COMU297) SAN PEDRO DE ATACAMA
COMU298) SAN PEDRO DE LA PAZ
COMU299) SAN RAFAEL
COMU300) SAN RAMON
COMU301) SAN ROSENDO
COMU302) SAN VICENTE
COMU303) SANTA BARBARA
COMU304) SANTA CRUZ
COMU305) SANTA JUANA
COMU306) SANTA MARIA
COMU307) SANTIAGO
COMU308) SANTO DOMINGO
COMU309) SIERRA GORDA
COMU310) TALAGANTE
COMU311) TALCA
COMU312) TALCAHUANO
COMU313) TALTAL
COMU314) TEMUCO
COMU315) TENO
COMU316) TEODORO SCHMIDT
COMU317) TIERRA AMARILLA
COMU318) TILTIL
COMU319) TIMAUKEL
COMU320) TIRUA
COMU321) TOCOPILLA
COMU322) TOLTEN
COMU323) TOME
COMU324) TORRES DEL PAINE
COMU325) TORTEL
COMU326) TRAIGUEN
COMU327) TREHUACO
COMU328) TUCAPEL
COMU329) VALDIVIA
COMU330) VALLENAR
COMU331) VALPARAISO
COMU332) VICHUQUEN
COMU333) VICTORIA
COMU334) VICUÑA
COMU335) VILCUN
COMU336) VILLA ALEGRE
COMU337) VILLA ALEMANA
COMU338) VILLARRICA
COMU339) VITACURA
COMU340) VIÑA DEL MAR
COMU341) YERBAS BUENAS
COMU342) YUMBEL
COMU343) YUNGAY
COMU344) ZAPALLAR
COMU345) ÑIQUEN
COMU346) ÑUÑOA

In [65]:
metadata = pd.read_csv("../data/digital-twin-chile-x/raw_data/final_meta_user_df.csv")
print(metadata.shape)
metadata.head()

(1908, 19)

,id,name,userName,location,url,description,followers,following,favouritesCount,statusesCount,mediaCount,createdAt,isVerified,isBlueVerified,protected,coverPicture,profilePicture,canDm,isAutomated
0,1.243992e+18,Johanna Santander,JoSantanderU,NaN,NaN,"Kinesiológa, docente, investigadora en Geronto...",14.0,45.0,133.0,73.0,3.0,2020-03-28T20:02:19.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/12439917...,https://pbs.twimg.com/profile_images/124412171...,False,False
1,8.288332e+07,Viviana,Ausipar,"Santiago, Pica, Arica.",NaN,"Profesora de historia, académica universitaria...",49.0,163.0,694.0,328.0,17.0,2009-10-16T13:51:55.000000Z,False,False,False,NaN,https://pbs.twimg.com/profile_images/144586857...,True,False
2,9.909042e+07,Francisco Araya,Pancho_Araya,Alto-Hospicio,NaN,NaN,9.0,0.0,0.0,3.0,0.0,2009-12-24T12:01:22.000000Z,False,False,False,NaN,https://pbs.twimg.com/profile_images/158678772...,False,False
3,1.136571e+08,Virginia ツ,virginia_tello,"Santiago, Chile",NaN,"Amo a mi familia, a mi compañero de vida y a n...",452.0,972.0,16244.0,3666.0,157.0,2010-02-12T15:25:22.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/11365709...,https://pbs.twimg.com/profile_images/174674281...,True,False
4,2.739562e+07,Dra. Vivian González,karen_koltrane,Santiago,NaN,NaN,874.0,468.0,14638.0,4700.0,92.0,2009-03-29T07:18:00.000000Z,False,False,True,https://pbs.twimg.com/profile_banners/27395623...,https://pbs.twimg.com/profile_images/148719438...,True,False

In [66]:
tweets = pd.read_csv("../data/digital-twin-chile-x/raw_data/final_tweets_user_df.csv")
print(tweets.shape)
tweets.head()

(27591, 23)

,tweet_id,tweet_url,tweet_text,tweet_created_at,tweet_lang,tweet_source,retweet_count,reply_count,like_count,quote_count,view_count,bookmark_count,is_reply,conversation_id,author_username,author_name,author_id,author_followers,author_following,author_location,author_verified,author_blue,author_created_at
0,1.945787e+18,https://x.com/__ffrvncisca/status/194578677279...,RT @AveAveces: El cerebro de mi mamá a mi edad...,Thu Jul 17 10:04:52 +0000 2025,es,Twitter for iPhone,9107,42,57501,163,765447,1082,False,1.945787e+18,__ffrvncisca,Fran,321421918,892,694,Chile,False,False,Tue Jun 21 15:07:21 +0000 2011
1,1.945494e+18,https://x.com/__ffrvncisca/status/194549399248...,"Hoy estaría viendo a Oasis en Manchester, pero...",Wed Jul 16 14:41:27 +0000 2025,es,Twitter for iPhone,0,0,2,0,84,0,False,1.945494e+18,__ffrvncisca,Fran,321421918,892,694,Chile,False,False,Tue Jun 21 15:07:21 +0000 2011
2,1.945088e+18,https://x.com/__ffrvncisca/status/194508845274...,RT @dedoindicee: Sinceramente no me preocupa n...,Tue Jul 15 11:49:59 +0000 2025,es,Twitter for iPhone,929,0,0,0,0,0,False,1.945088e+18,__ffrvncisca,Fran,321421918,892,694,Chile,False,False,Tue Jun 21 15:07:21 +0000 2011
3,1.944907e+18,https://x.com/__ffrvncisca/status/194490733559...,RT @fuumando: Descripción gráfica de Lunes 14 ...,Mon Jul 14 23:50:18 +0000 2025,es,Twitter for iPhone,8505,32,20015,303,908816,277,False,1.944907e+18,__ffrvncisca,Fran,321421918,892,694,Chile,False,False,Tue Jun 21 15:07:21 +0000 2011
4,1.944584e+18,https://x.com/__ffrvncisca/status/194458397009...,"RT @luumbrera: perdón bro no podré ir, me surg...",Mon Jul 14 02:25:21 +0000 2025,es,Twitter for iPhone,15567,41,57409,468,1350949,1790,False,1.944584e+18,__ffrvncisca,Fran,321421918,892,694,Chile,False,False,Tue Jun 21 15:07:21 +0000 2011

In [ ]:
account_list = [account for account in metadata["userName"].unique() if account in tweets["author_username"].unique()]
account_list = account_list[:5]
len(account_list)

10

In [ ]:
filtered_metadata = metadata[metadata["userName"].isin(account_list)].reset_index(drop=True)
filtered_metadata.rename(columns={
    "profilePicture":"profile_picture",
    "userName":"account_id",
    # "createdAt":"created_at",
    "isVerified":"is_verified",
    "isBlueVerified":"is_blue_verified",
    "statusesCount":"statuses_count",
    "favouritesCount":"favourites_count",
    "mediaCount":"media_count",
}, 
inplace=True)
filtered_metadata.to_csv("../data/digital-twin-chile-x/profile_metadata_test.csv", index=False)
filtered_metadata.head()

,id,name,account_id,location,url,description,followers,following,favourites_count,statuses_count,media_count,createdAt,is_verified,is_blue_verified,protected,coverPicture,profile_picture,canDm,isAutomated
0,1.243992e+18,Johanna Santander,JoSantanderU,NaN,NaN,"Kinesiológa, docente, investigadora en Geronto...",14.0,45.0,133.0,73.0,3.0,2020-03-28T20:02:19.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/12439917...,https://pbs.twimg.com/profile_images/124412171...,False,False
1,8.288332e+07,Viviana,Ausipar,"Santiago, Pica, Arica.",NaN,"Profesora de historia, académica universitaria...",49.0,163.0,694.0,328.0,17.0,2009-10-16T13:51:55.000000Z,False,False,False,NaN,https://pbs.twimg.com/profile_images/144586857...,True,False
2,1.136571e+08,Virginia ツ,virginia_tello,"Santiago, Chile",NaN,"Amo a mi familia, a mi compañero de vida y a n...",452.0,972.0,16244.0,3666.0,157.0,2010-02-12T15:25:22.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/11365709...,https://pbs.twimg.com/profile_images/174674281...,True,False
3,4.031052e+08,Bárbara Echeverría Álvarez,BV_Echeverria,NaN,NaN,"26 años, Periodista, trabajo en Comunicaciones...",456.0,1078.0,394.0,1339.0,12.0,2011-11-02T01:13:54.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/40310521...,https://pbs.twimg.com/profile_images/127421463...,False,False
4,3.698330e+07,Miguel L,Manu_28,Chile,NaN,NaN,50.0,499.0,136.0,239.0,32.0,2009-05-01T16:42:11.000000Z,False,False,False,https://pbs.twimg.com/profile_banners/36983299...,https://pbs.twimg.com/profile_images/135103505...,False,False

In [ ]:
filtered_tweets = tweets[tweets["author_username"].isin(account_list)].reset_index(drop=True)
filtered_tweets.rename(columns={
    "tweet_created_at":"createdAt",
    "tweet_text":"text",
    "like_count":"likeCount",
    "view_count":"viewCount",
    "retweet_count":"retweetCount",
    "reply_count":"replyCount",
    "quote_count":"quoteCount",
    "bookmark_count":"bookmarkCount",
    "tweet_lang":"lang",
    "author_username":"account_id",
}, 
inplace=True)
filtered_tweets.to_csv("../data/digital-twin-chile-x/profile_tweets_test.csv", index=False)
filtered_tweets.head()

,tweet_id,tweet_url,text,createdAt,lang,tweet_source,retweetCount,replyCount,likeCount,quoteCount,viewCount,bookmarkCount,is_reply,conversation_id,account_id,author_name,author_id,author_followers,author_following,author_location,author_verified,author_blue,author_created_at
0,1.602493e+18,https://x.com/Ausipar/status/1602493130929995779,Por Peñalolen mucho olor a quemado… ¿algún inc...,Tue Dec 13 02:38:29 +0000 2022,es,Twitter for iPhone,0,0,0,0,0,0,False,1.602493e+18,Ausipar,Viviana,82883325,49,163,"Santiago, Pica, Arica.",False,False,Fri Oct 16 13:51:55 +0000 2009
1,1.546166e+18,https://x.com/Ausipar/status/1546165941460877312,Químicos permanentes https://t.co/qJCuunsxHd #...,Sun Jul 10 16:14:21 +0000 2022,es,Twitter for iPhone,0,0,0,0,0,0,False,1.546166e+18,Ausipar,Viviana,82883325,49,163,"Santiago, Pica, Arica.",False,False,Fri Oct 16 13:51:55 +0000 2009
2,1.528952e+18,https://x.com/Ausipar/status/1528952296372961281,El que este libre de pecado que tire la primer...,Tue May 24 04:13:28 +0000 2022,es,Twitter for iPhone,0,0,0,0,0,0,False,1.528952e+18,Ausipar,Viviana,82883325,49,163,"Santiago, Pica, Arica.",False,False,Fri Oct 16 13:51:55 +0000 2009
3,1.527256e+18,https://x.com/Ausipar/status/1527256469380272133,Viruela del mono… afírmense ciudadanxs!! Se no...,Thu May 19 11:54:52 +0000 2022,es,Twitter for iPhone,0,0,0,0,0,0,False,1.527256e+18,Ausipar,Viviana,82883325,49,163,"Santiago, Pica, Arica.",False,False,Fri Oct 16 13:51:55 +0000 2009
4,1.527255e+18,https://x.com/Ausipar/status/1527254977181192192,Corregir pruebas es lejos lo mas agotador de l...,Thu May 19 11:48:56 +0000 2022,es,Twitter for iPhone,0,0,0,0,0,0,False,1.527255e+18,Ausipar,Viviana,82883325,49,163,"Santiago, Pica, Arica.",False,False,Fri Oct 16 13:51:55 +0000 2009